### ISSUE TITLE
💡 [REQUEST] - Option to add a past workout/training

### ISSUE THREAD

**Issue by jwallet** [madmustachecompany/Blast-Workout-App#48]
### Summary

Since there are graphs and tracking in the app. I would like to be able to log training that I did without starting the workout from the app. I may not have the app with me at all time, but I will like to come back to it at night and enter a past activity that I did with a friend just so it tracks my body hest map.

### Basic Example

Maybe move training history to the tracking page I think it will make more sense or add a new tab related to Records/Logs so I can view the calendar right away and be able to track what I did. After all seeing past logs that is what makes us proud and you should focus on that, like Personal records and graphs and stats about previous trainings #14 #18 #19. Reward customers  efforts

**Comment by noelielc** [comment]
We're going to add the possibility of changing the date of completed training sessions. This will help solve part of the problem.

So, to record a workout in the past, the procedure is as follows: 
- start an empty workout or routine
- finish the workout by pressing the "finish" button and selecting "validate all sets"
- in the top-right menu of the page showing details of the completed workout, choose the "change date" option
- select an earlier date and validate the change

Should be available in next release.

**Comment by noelielc** [comment]
published, version 1.54
