### ISSUE TITLE
🐛 [BUG] - Crash when editing completed workout

### ISSUE THREAD

**Issue by jwallet** [madmustachecompany/Blast-Workout-App#50]
### Description

App crashes when editing a workout when navigating from a routine to the max PR to the actual recorded workout
 
Only the Deadlift exercise works (only exercise in the list that did not use this routine), all others navigates but their workouts cannot be edited.

For what I see, I cannot edit a past workout that has the same name than my routine. Maybe I cannot navigate because there is a cycling dependency.

Flow:
- open Routine A
- edit Routine A
- open Past workout A (recorded using Routine A)
- edit Past workout A (maybe tries to reopen the same first page but navigation fails because it will loose the first screen in his flow?)

### Reproduction steps

1. Go to routine
1.  Edit routine
1. Tap on an activity with a Max Rep info on
1. Edit the workout
1. App crashes

### Screenshots

https://github.com/madmustachecompany/Blast-Workout-App/assets/23088305/f0fbbec9-fe00-4f26-a982-4bdb452b969f

### Actual workout 

![Screenshot_20230727-081228_Blast.jpg](https://github.com/madmustachecompany/Blast-Workout-App/assets/23088305/f9607e27-c4e1-4f15-8259-4e53de949591)

![Screenshot_20230727-081232_Blast.jpg](https://github.com/madmustachecompany/Blast-Workout-App/assets/23088305/ef58e0ba-941e-4e24-a891-3f660bd061e9)

### OS

Android

**Comment by noelielc** [comment]
Good catch. 
This has been fixed and will be rolled out in the next release (v1.53).
