### ISSUE TITLE
💡 [REQUEST] - Add custom exercise 

### ISSUE THREAD

**Issue by Sasukenshin** [madmustachecompany/Blast-Workout-App#52]
### Summary

Possibility to write down any exercises even if you don't calculate calories or time for the training. But just let me write my forearm exercises please 🥺.

### Basic Example

Possibility to add 3 set of 10 wrist flexion or to add jumping rope as warmup

**Comment by jwallet** [comment]
I feel you man. Currently using planking to be able to log my hanging exercise.

If you need a picture for the exercise, I'm sure just a capture of the focus group will be fine using the heatmap  body guy.

However I will need to be able to select between weight/reps and weight/time. Also select the focus group like forearms

Make it possible <3

**Comment by noelielc** [comment]
closed in favour of #28

**Comment by noelielc** [comment]
Forearms exercises added in v1.57 (coming soon):
- wrist curl (flexion)
- reverted wrist curl (extension)
- dead hang (isometric bodyweight hold)
