### ISSUE TITLE
💡 [REQUEST] - Exercice : cardio > escalier

### ISSUE THREAD

**Issue by PorkyMcFry** [madmustachecompany/Blast-Workout-App#54]
### Summary

il serait chouette de pouvoir ajouter l'exercice cardio : Escalier

### Basic Example

 sur machine stairmaster ou plein air
> durée 
> distance

**Comment by noelielc** [comment]
Suggestion ajoutée à la liste des exercices manquants.

_Issue closed in favour of #38_

**Comment by madmustachecompany** [comment]
Added in the last update, version 1.63
