### ISSUE TITLE
💡 [REQUEST] - <ajouter un exercice>

### ISSUE THREAD

**Issue by PorkyMcFry** [madmustachecompany/Blast-Workout-App#56]
### Summary

il serait chouette de pouvoir ajouter manuellement un exercice à sa routine. Personnaliser son entraînement avec des exercices que l'on choisit soit même 

### Basic Example

fonction d'ajout manuel d'exercice
> 1 icône générale, pas besoin d'en développer 36
> choix du nom
> choix de la zone du corps
> choix du poid / distance / temps

**Comment by noelielc** [comment]
_Merci pour la suggestion. C'est une fonctionnalité qui est régulièrement demandée et qui est en projet._

This feature has already been requested, closing issue in favour of #28
