### ISSUE TITLE
💡 [REQUEST] - can it provide an option to input measurements in cm?

### ISSUE THREAD

**Issue by sheunglys** [madmustachecompany/Blast-Workout-App#62]
### Summary

Currently showing inch , and cant find how to change to cm

**Comment by sheunglys** [comment]
![Screenshot_20231020_073300_Blast](https://github.com/madmustachecompany/Blast-Workout-App/assets/12569202/50d6bafa-c2ae-4f10-b7ff-3470621aed53)
And can it be simply input but not a slider?

**Comment by noelielc** [comment]
The unit of measurement is defined during onboarding, and there seems to be no option to redefine it afterwards 🫢
We're going to add an option in the parameters to be able to modify them later, as for the weight unit or gender. This is an oversight on our part.

**Comment by sheunglys** [comment]
> The unit of measurement is defined during onboarding, and there seems to be no option to redefine it afterwards 🫢 We're going to add an option in the parameters to be able to modify them later, as for the weight unit or gender. This is an oversight on our part.

Thanks! It would be great to be able to modify it like weight unit!

**Comment by noelielc** [comment]
New release (v1.56), it's now possible to change length and distance units in the settings:

![IMG_DF3C9F498F78-1](https://github.com/madmustachecompany/Blast-Workout-App/assets/109250619/12d8ca06-6e27-4e56-a4f6-4175b20473b8)
