### ISSUE TITLE
Allow user to choose "Bodyweight" as the weight of training for a set

### ISSUE THREAD

**Issue by TheSecondWing** [madmustachecompany/Blast-Workout-App#71]
### Summary

Hello,
Could you please allow the user to choose "bodyweight" for the weight of the exercises?
Thanks.

### Basic Example

While doing bodyweight planks for example I usually write down "0" as a weight, but I think that could bettered.

**Comment by madmustachecompany** [comment]
Hi @TheSecondWing,
I appreciate that this feature can be improved, but I'm not sure I understand your suggestion. Could you please be more specific about what you're expecting?

Here are some explanations of how bodyweight exercises are considered within the app:
Entering 0 in the weight field is what is expected when bodyweight exercise, such as plank, is performed without additional load.
Some bodyweight exercises allow for weights to be added (which may be "unconventional" or unavailable, such as weight belts, ankle weights, etc) and that is where the weight field may be used.
Bodyweight is considered as equipment (i.e. a type of resistance) and does not affect the type of exercise "repetition + load" or "duration + load".

Thanks

**Comment by TheSecondWing** [comment]
Hi.

My bad. I didn't realize that bodyweight was in the equipment section.

That makes sense!

We can close this ticket. My question has been answered.

Thanks!
