### ISSUE TITLE
🐛 [BUG] 

### ISSUE THREAD

**Issue by Brandon7811** [madmustachecompany/Blast-Workout-App#73]
### Description

Google fit connection doesn't work. 

![Screenshot_20240109_164344_Google Play services](https://github.com/madmustachecompany/Blast-Workout-App/assets/157553690/25ac72d6-cf5b-45ab-9735-cb668933015b)

### Reproduction steps

```bash
1. Go to 'Settings'
2. Scroll down to "Google Fit"
3. Tap on 'Google fit'
4. Click on connect/associate
5. See error
```

### Screenshots

```bash
![Screenshot_20240109_164344_Google Play services](https://github.com/madmustachecompany/Blast-Workout-App/assets/157553690/25ac72d6-cf5b-45ab-9735-cb668933015b
```

### OS

Android

**Comment by madmustachecompany** [comment]
This issue has been reported > #66 
We are currently working with Google to unlock the permissions but we are still waiting for their approval. Unfortunately we have no information on how long this may take.
I'm closing this ticket in favour of the previous one, thank you for your feedback.
