### ISSUE TITLE
🐛 [BUG] - Sets to failure do not appear in New Records

### ISSUE THREAD

**Issue by TheSecondWing** [madmustachecompany/Blast-Workout-App#76]
### Description

At the end of a workout, a screen appears to showcase the new records in terms of volume and weight.

Sets to failure do not seems to be taken into account for this.

See pictures attached. First time doing 160kg for an exercise, but because it is a set to failure it does not appear in the New Records screen at the end of the workout.

Might be the same for dropsets, have not tested.

### Reproduction steps

```bash
1. Go to '...'
2. Tap on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Android

**Comment by TheSecondWing** [comment]
![Screenshot_20240213-215451](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/0ac8650d-758d-4c5b-ad30-26d87979540e)
![Screenshot_20240213-215457](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/0b41e0d6-4978-478c-a747-d0edf717b31f)

**Comment by TheSecondWing** [comment]
Tested: if I transform it in a Normal Set it is taken into account and the New Records tab updates; so it really seems to be linked to the Set to Failure status.

**Comment by TheSecondWing** [comment]
Tested: if I transform it in a Normal Set it is taken into account and the New Records tab updates; so it really seems to be linked to the Set to Failure status.

Tested: problem does not seem to be limited in terms of exercises. I also reproduce for Lat Pulldowns. I have a personal best in terms of weight that is a Set to Failure of 65kg, that does not appear in the New Records tab.

**Comment by madmustachecompany** [comment]
Thanks for this report, we'll take a look.

**Comment by madmustachecompany** [comment]
Hi @TheSecondWing,

The next release (v1.62) should fix this issue. If this is not the case, please let us know.

**Comment by TheSecondWing** [comment]
Hi @madmustachecompany

Problem seems to be fixed. The release also corrected the New Records tabs concerned retroactively.

Thanks!
