### ISSUE TITLE
💡 [REQUEST] - Add personal exercices

### ISSUE THREAD

**Issue by jonylordagonie** [madmustachecompany/Blast-Workout-App#84]
### Summary

Juste have a fonction to create our personal exercices. Some exercices dosen't exist on the app and have this fonction Can bé great to créat our set with exercices who whe want to do and dosen't exist on the app 

### Basic Example

Create a New exercices.
Title : Jumping Jack
Icon: chose an icon
Muscle: cardio
Description : jump jump jump

**Comment by madmustachecompany** [comment]
This is on development ([#28](https://github.com/madmustachecompany/Blast-Workout-App/issues/28)),
will be available soon 🙌

**Comment by madmustachecompany** [comment]
Custom exercise feature has been released (version 1.70)
