### ISSUE TITLE
🐛 [BUG] - waist tracker upper limit

### ISSUE THREAD

**Issue by psychicash** [madmustachecompany/Blast-Workout-App#86]
### Description

There seems to be an upper limit of 52.8 on the waist measurement.  Largest recorded was 119. 52.8 feels arbitrary. It does limit some users from recording their waist and seeing progress. 

### Reproduction steps

```bash
1. Go to '...'
2. Tap on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Android

**Comment by madmustachecompany** [comment]
Hi @psychicash,

You've probably set your measurements in imperial (in) format instead of metric (cm). Waist measurement values range from 52.3 to 131.9 cm (corresponding to a range of 19.3 to 52.9 inches), which should be sufficient.

Can you please check in your settings and let us know whether this solves the problem or not?

**Comment by psychicash** [comment]
> Hi @psychicash,
> 
> You've probably set your measurements in imperial (in) format instead of metric (cm). Waist measurement values range from 52.3 to 131.9 cm (corresponding to a range of 19.3 to 52.9 inches), which should be sufficient.
> 
> Can you please check in your settings and let us know whether this solves the problem or not?

While I do have it set to imperial (in), my waist measurement when I started was over 60 inches. I'm now around 57 inches. I'm sure I'm not the only person. I realize that someone like me is a huge minority of your user base (pun intended). As a user, this presented to me as a bug.

**Comment by madmustachecompany** [comment]
Hi @psychicash,

We had to set limits for stability reasons, but these were chosen somewhat abstractly (and awkwardly). We're going to modify these limits and bring them closer to the min and max recorded values (15 to 119 inches), as you suggested and which seems indeed more relevant to represent the extremes.

We have no intention of excluding any users, and are sorry for any inconvenience caused. 
Thank you for sharing your experience with us. Getting feedback and being able to discuss it with you is a valuable source of improvement, so please don't hesitate to continue to share any further comments you may have 👍.

**Comment by psychicash** [comment]
> Hi @psychicash,
> 
> We had to set limits for stability reasons, but these were chosen somewhat abstractly (and awkwardly). We're going to modify these limits and bring them closer to the min and max recorded values (15 to 119 inches), as you suggested and which seems indeed more relevant to represent the extremes.
> 
> We have no intention of excluding any users, and are sorry for any inconvenience caused. Thank you for sharing your experience with us. Getting feedback and being able to discuss it with you is a valuable source of improvement, so please don't hesitate to continue to share any further comments you may have 👍.

I completely understand. I didn't assume that you were excluding anyone. I thought it was a bug but I understand where you're coming from. I look forward to seeing the app improve. I love the app and am excited about the roadmap. Keep it up !!! I'll let you know if I find anything else.

**Comment by madmustachecompany** [comment]
@psychicash
With version 1.71, we have updated the measurement ranges (including the maximum waist circumference increase).
This problem should now be solved. Thank you for your contribution 👍.
